name: Auto Update Token & Playlist (Selected Categories)

on:
  schedule:
    - cron: '0 * * * *'   # Every 1 hour
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate new token and playlist
      env:
        XOTT_API_URL: ${{ secrets.XOTT_API_URL }}
      run: python generate_playlist.py

    - name: Commit and push updates
      run: |
        git config --global user.name "actions-bot"
        git config --global user.email "actions@github.com"
        git add token.json playlist.m3u
        git commit -m "🔁 Auto update token & playlist (Selected) $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
